---
# Set Group Write Permissions on ORACLE_HOME/dbs for all installed ORACLE_HOMEs
# Executed only if delphix_user is not equal to "oracle"

- name: Setting Group Permission on ORACLE_HOME/dbs
  file:
    path: "{{ item.item }}/dbs"
    mode: g+w
  loop: "{{ existing_dbhome_with_owner.results }}"
  when: item.stat.pw_name != delphix_user
