#
# Copyright (c) 2019 by Delphix. All rights reserved.
#

---

- name: Check if 32-bit runtime is installed
  shell: |
    set -o pipefail
    dpkg --print-foreign-architectures | grep i386
  args:
    executable: /bin/bash
  register: result_32bit
  changed_when: result_32bit.rc == 1
  failed_when: result_32bit.rc > 1

- name: Enable 32-bit runtime
  command: dpkg --add-architecture i386
  when: result_32bit.rc == 1

- name: Install required packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
