---
#
# Copyright (c) 2018 by Delphix. All rights reserved.
#

- name: Install required packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    # Required for mounting NFS filesystems
    - nfs-utils
