---
#
# Copyright (c) 2018 by Delphix. All rights reserved.
#

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      # Required for mounting NFS filesystems
      - nfs-utils
