#
# Copyright (c) 2019 by Delphix. All rights reserved.
#
---

- name: Install required packages
  yum:
    name: "{{ packages }}"
    state: present
    update_cache: true
  register: task_result
  until: task_result is success
  retries: 3
  delay: 2
